#占位符名的刷新速度
#变量名的刷新速度
#越小消耗越大
updateTick: 5

##使用宝可梦自己的输入框,确保你没有其他插件会和输入框冲突(反正我不会某皮肤插件需要补丁)
##使用宝可梦的输入栏输入上线比原版Mc的上线低,建议这里填false
usePokeInput: false

#改名卡
card:
  #支持数字id加:id
  material: PAPER
  name: '改名卡'
  lore:
    - '对自己的宝可梦使用即可修改自己宝可梦名字'
    - '右键使用后在输入框中输入想要的名字[可以是变量]'

#Msg
msg:
  help:
    - "HELP========"
    - "/pfname rename [player] [slot] [name...] 直接修改名字"
    - "/pfname reload 重载配置"
    - "/pfname help 帮助"
    - "/pfname givecard [1-64] 给与改名卡"
  rename_success: "已成功修改精灵的名字为 {name}"
  already_used_rename_card: '已使用过一次改名卡,先成功改名一次,或者退出游戏自动退还改名卡'
  use_rename_card: '请在输入栏内输入需要改的名字'

