#占位符名的刷新速度
#变量名的刷新速度
updateTick: 5

##使用宝可梦自己的输入框,确保你没有其他插件会和输入框冲突(反正我不会某皮肤插件需要补丁)
##使用宝可梦的输入栏输入上线比原版Mc的上线低,建议这里填false
usePokeInput: false

#改名卡
card:
  #支持数字id加:id
  material: PAPER
  name: '改名卡'
  lore:
    - '对自己的宝可梦使用即可修改自己宝可梦名字'
    - '右键使用后在输入框中输入想要的名字[可以是变量]'